version: "3"
services:
  web:
    container_name: be-jobsterific
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - mysql
  mysql:
    container_name: db-jobsterific
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysqla
      - ./db/root_password.txt:/run/secrets/mysql_root_password
      - ./db/database_name.txt:/run/secrets/mysql_database
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
