version: "3"
services:
  web:
    container_name: be-jobsterific
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - mysql
  mysql:
    container_name: db-jobsterific
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      
volumes:
  db-data:
